CREATE PROCEDURE setup.Country
AS
EXEC SaveClassifierType 'Country', 'Country', 'An ISO 3166 two-letter country code.'
EXEC SaveClassifier 'Country', 'AF', 'Afghanistan';
EXEC SaveClassifier 'Country', 'AX', 'Åland Islands';
EXEC SaveClassifier 'Country', 'AL', 'Albania';
EXEC SaveClassifier 'Country', 'DZ', 'Algeria';
EXEC SaveClassifier 'Country', 'AS', 'American Samoa';
EXEC SaveClassifier 'Country', 'AD', 'Andorra';
EXEC SaveClassifier 'Country', 'AO', 'Angola';
EXEC SaveClassifier 'Country', 'AI', 'Anguilla';
EXEC SaveClassifier 'Country', 'AQ', 'Antarctica';
EXEC SaveClassifier 'Country', 'AG', 'Antigua and Barbuda';
EXEC SaveClassifier 'Country', 'AR', 'Argentina';
EXEC SaveClassifier 'Country', 'AM', 'Armenia';
EXEC SaveClassifier 'Country', 'AW', 'Aruba';
EXEC SaveClassifier 'Country', 'AU', 'Australia';
EXEC SaveClassifier 'Country', 'AT', 'Austria';
EXEC SaveClassifier 'Country', 'AZ', 'Azerbaijan';
EXEC SaveClassifier 'Country', 'BS', 'Bahamas (the)';
EXEC SaveClassifier 'Country', 'BH', 'Bahrain';
EXEC SaveClassifier 'Country', 'BD', 'Bangladesh';
EXEC SaveClassifier 'Country', 'BB', 'Barbados';
EXEC SaveClassifier 'Country', 'BY', 'Belarus';
EXEC SaveClassifier 'Country', 'BE', 'Belgium';
EXEC SaveClassifier 'Country', 'BZ', 'Belize';
EXEC SaveClassifier 'Country', 'BJ', 'Benin';
EXEC SaveClassifier 'Country', 'BM', 'Bermuda';
EXEC SaveClassifier 'Country', 'BT', 'Bhutan';
EXEC SaveClassifier 'Country', 'BO', 'Bolivia (Plurinational State of)';
EXEC SaveClassifier 'Country', 'BQ', 'Bonaire, Sint Eustatius and Saba';
EXEC SaveClassifier 'Country', 'BA', 'Bosnia and Herzegovina';
EXEC SaveClassifier 'Country', 'BW', 'Botswana';
EXEC SaveClassifier 'Country', 'BV', 'Bouvet Island';
EXEC SaveClassifier 'Country', 'BR', 'Brazil';
EXEC SaveClassifier 'Country', 'IO', 'British Indian Ocean Territory (the)';
EXEC SaveClassifier 'Country', 'BN', 'Brunei Darussalam';
EXEC SaveClassifier 'Country', 'BG', 'Bulgaria';
EXEC SaveClassifier 'Country', 'BF', 'Burkina Faso';
EXEC SaveClassifier 'Country', 'BI', 'Burundi';
EXEC SaveClassifier 'Country', 'CV', 'Cabo Verde';
EXEC SaveClassifier 'Country', 'KH', 'Cambodia';
EXEC SaveClassifier 'Country', 'CM', 'Cameroon';
EXEC SaveClassifier 'Country', 'CA', 'Canada';
EXEC SaveClassifier 'Country', 'KY', 'Cayman Islands (the)';
EXEC SaveClassifier 'Country', 'CF', 'Central African Republic (the)';
EXEC SaveClassifier 'Country', 'TD', 'Chad';
EXEC SaveClassifier 'Country', 'CL', 'Chile';
EXEC SaveClassifier 'Country', 'CN', 'China';
EXEC SaveClassifier 'Country', 'CX', 'Christmas Island';
EXEC SaveClassifier 'Country', 'CC', 'Cocos (Keeling) Islands (the)';
EXEC SaveClassifier 'Country', 'CO', 'Colombia';
EXEC SaveClassifier 'Country', 'KM', 'Comoros (the)';
EXEC SaveClassifier 'Country', 'CD', 'Congo (the Democratic Republic of the)';
EXEC SaveClassifier 'Country', 'CG', 'Congo (the)';
EXEC SaveClassifier 'Country', 'CK', 'Cook Islands (the)';
EXEC SaveClassifier 'Country', 'CR', 'Costa Rica';
EXEC SaveClassifier 'Country', 'CI', 'Côte d''Ivoire';
EXEC SaveClassifier 'Country', 'HR', 'Croatia';
EXEC SaveClassifier 'Country', 'CU', 'Cuba';
EXEC SaveClassifier 'Country', 'CW', 'Curaçao';
EXEC SaveClassifier 'Country', 'CY', 'Cyprus';
EXEC SaveClassifier 'Country', 'CZ', 'Czechia';
EXEC SaveClassifier 'Country', 'DK', 'Denmark';
EXEC SaveClassifier 'Country', 'DJ', 'Djibouti';
EXEC SaveClassifier 'Country', 'DM', 'Dominica';
EXEC SaveClassifier 'Country', 'DO', 'Dominican Republic (the)';
EXEC SaveClassifier 'Country', 'EC', 'Ecuador';
EXEC SaveClassifier 'Country', 'EG', 'Egypt';
EXEC SaveClassifier 'Country', 'SV', 'El Salvador';
EXEC SaveClassifier 'Country', 'GQ', 'Equatorial Guinea';
EXEC SaveClassifier 'Country', 'ER', 'Eritrea';
EXEC SaveClassifier 'Country', 'EE', 'Estonia';
EXEC SaveClassifier 'Country', 'SZ', 'Eswatini';
EXEC SaveClassifier 'Country', 'ET', 'Ethiopia';
EXEC SaveClassifier 'Country', 'FK', 'Falkland Islands (the) [Malvinas]';
EXEC SaveClassifier 'Country', 'FO', 'Faroe Islands (the)';
EXEC SaveClassifier 'Country', 'FJ', 'Fiji';
EXEC SaveClassifier 'Country', 'FI', 'Finland';
EXEC SaveClassifier 'Country', 'FR', 'France';
EXEC SaveClassifier 'Country', 'GF', 'French Guiana';
EXEC SaveClassifier 'Country', 'PF', 'French Polynesia';
EXEC SaveClassifier 'Country', 'TF', 'French Southern Territories (the)';
EXEC SaveClassifier 'Country', 'GA', 'Gabon';
EXEC SaveClassifier 'Country', 'GM', 'Gambia (the)';
EXEC SaveClassifier 'Country', 'GE', 'Georgia';
EXEC SaveClassifier 'Country', 'DE', 'Germany';
EXEC SaveClassifier 'Country', 'GH', 'Ghana';
EXEC SaveClassifier 'Country', 'GI', 'Gibraltar';
EXEC SaveClassifier 'Country', 'GR', 'Greece';
EXEC SaveClassifier 'Country', 'GL', 'Greenland';
EXEC SaveClassifier 'Country', 'GD', 'Grenada';
EXEC SaveClassifier 'Country', 'GP', 'Guadeloupe';
EXEC SaveClassifier 'Country', 'GU', 'Guam';
EXEC SaveClassifier 'Country', 'GT', 'Guatemala';
EXEC SaveClassifier 'Country', 'GG', 'Guernsey';
EXEC SaveClassifier 'Country', 'GN', 'Guinea';
EXEC SaveClassifier 'Country', 'GW', 'Guinea-Bissau';
EXEC SaveClassifier 'Country', 'GY', 'Guyana';
EXEC SaveClassifier 'Country', 'HT', 'Haiti';
EXEC SaveClassifier 'Country', 'HM', 'Heard Island and McDonald Islands';
EXEC SaveClassifier 'Country', 'VA', 'Holy See (the)';
EXEC SaveClassifier 'Country', 'HN', 'Honduras';
EXEC SaveClassifier 'Country', 'HK', 'Hong Kong';
EXEC SaveClassifier 'Country', 'HU', 'Hungary';
EXEC SaveClassifier 'Country', 'IS', 'Iceland';
EXEC SaveClassifier 'Country', 'IN', 'India';
EXEC SaveClassifier 'Country', 'ID', 'Indonesia';
EXEC SaveClassifier 'Country', 'IR', 'Iran (Islamic Republic of)';
EXEC SaveClassifier 'Country', 'IQ', 'Iraq';
EXEC SaveClassifier 'Country', 'IE', 'Ireland';
EXEC SaveClassifier 'Country', 'IM', 'Isle of Man';
EXEC SaveClassifier 'Country', 'IL', 'Israel';
EXEC SaveClassifier 'Country', 'IT', 'Italy';
EXEC SaveClassifier 'Country', 'JM', 'Jamaica';
EXEC SaveClassifier 'Country', 'JP', 'Japan';
EXEC SaveClassifier 'Country', 'JE', 'Jersey';
EXEC SaveClassifier 'Country', 'JO', 'Jordan';
EXEC SaveClassifier 'Country', 'KZ', 'Kazakhstan';
EXEC SaveClassifier 'Country', 'KE', 'Kenya';
EXEC SaveClassifier 'Country', 'KI', 'Kiribati';
EXEC SaveClassifier 'Country', 'KP', 'Korea (the Democratic People''s Republic of)';
EXEC SaveClassifier 'Country', 'KR', 'Korea (the Republic of)';
EXEC SaveClassifier 'Country', 'KW', 'Kuwait';
EXEC SaveClassifier 'Country', 'KG', 'Kyrgyzstan';
EXEC SaveClassifier 'Country', 'LA', 'Lao People''s Democratic Republic (the)';
EXEC SaveClassifier 'Country', 'LV', 'Latvia';
EXEC SaveClassifier 'Country', 'LB', 'Lebanon';
EXEC SaveClassifier 'Country', 'LS', 'Lesotho';
EXEC SaveClassifier 'Country', 'LR', 'Liberia';
EXEC SaveClassifier 'Country', 'LY', 'Libya';
EXEC SaveClassifier 'Country', 'LI', 'Liechtenstein';
EXEC SaveClassifier 'Country', 'LT', 'Lithuania';
EXEC SaveClassifier 'Country', 'LU', 'Luxembourg';
EXEC SaveClassifier 'Country', 'MO', 'Macao';
EXEC SaveClassifier 'Country', 'MK', 'Macedonia (the former Yugoslav Republic of)';
EXEC SaveClassifier 'Country', 'MG', 'Madagascar';
EXEC SaveClassifier 'Country', 'MW', 'Malawi';
EXEC SaveClassifier 'Country', 'MY', 'Malaysia';
EXEC SaveClassifier 'Country', 'MV', 'Maldives';
EXEC SaveClassifier 'Country', 'ML', 'Mali';
EXEC SaveClassifier 'Country', 'MT', 'Malta';
EXEC SaveClassifier 'Country', 'MH', 'Marshall Islands (the)';
EXEC SaveClassifier 'Country', 'MQ', 'Martinique';
EXEC SaveClassifier 'Country', 'MR', 'Mauritania';
EXEC SaveClassifier 'Country', 'MU', 'Mauritius';
EXEC SaveClassifier 'Country', 'YT', 'Mayotte';
EXEC SaveClassifier 'Country', 'MX', 'Mexico';
EXEC SaveClassifier 'Country', 'FM', 'Micronesia (Federated States of)';
EXEC SaveClassifier 'Country', 'MD', 'Moldova (the Republic of)';
EXEC SaveClassifier 'Country', 'MC', 'Monaco';
EXEC SaveClassifier 'Country', 'MN', 'Mongolia';
EXEC SaveClassifier 'Country', 'ME', 'Montenegro';
EXEC SaveClassifier 'Country', 'MS', 'Montserrat';
EXEC SaveClassifier 'Country', 'MA', 'Morocco';
EXEC SaveClassifier 'Country', 'MZ', 'Mozambique';
EXEC SaveClassifier 'Country', 'MM', 'Myanmar';
EXEC SaveClassifier 'Country', 'NA', 'Namibia';
EXEC SaveClassifier 'Country', 'NR', 'Nauru';
EXEC SaveClassifier 'Country', 'NP', 'Nepal';
EXEC SaveClassifier 'Country', 'NL', 'Netherlands (the)';
EXEC SaveClassifier 'Country', 'NC', 'New Caledonia';
EXEC SaveClassifier 'Country', 'NZ', 'New Zealand';
EXEC SaveClassifier 'Country', 'NI', 'Nicaragua';
EXEC SaveClassifier 'Country', 'NE', 'Niger (the)';
EXEC SaveClassifier 'Country', 'NG', 'Nigeria';
EXEC SaveClassifier 'Country', 'NU', 'Niue';
EXEC SaveClassifier 'Country', 'NF', 'Norfolk Island';
EXEC SaveClassifier 'Country', 'MP', 'Northern Mariana Islands (the)';
EXEC SaveClassifier 'Country', 'NO', 'Norway';
EXEC SaveClassifier 'Country', 'OM', 'Oman';
EXEC SaveClassifier 'Country', 'PK', 'Pakistan';
EXEC SaveClassifier 'Country', 'PW', 'Palau';
EXEC SaveClassifier 'Country', 'PS', 'Palestine, State of';
EXEC SaveClassifier 'Country', 'PA', 'Panama';
EXEC SaveClassifier 'Country', 'PG', 'Papua New Guinea';
EXEC SaveClassifier 'Country', 'PY', 'Paraguay';
EXEC SaveClassifier 'Country', 'PE', 'Peru';
EXEC SaveClassifier 'Country', 'PH', 'Philippines (the)';
EXEC SaveClassifier 'Country', 'PN', 'Pitcairn';
EXEC SaveClassifier 'Country', 'PL', 'Poland';
EXEC SaveClassifier 'Country', 'PT', 'Portugal';
EXEC SaveClassifier 'Country', 'PR', 'Puerto Rico';
EXEC SaveClassifier 'Country', 'QA', 'Qatar';
EXEC SaveClassifier 'Country', 'RE', 'Réunion';
EXEC SaveClassifier 'Country', 'RO', 'Romania';
EXEC SaveClassifier 'Country', 'RU', 'Russian Federation (the)';
EXEC SaveClassifier 'Country', 'RW', 'Rwanda';
EXEC SaveClassifier 'Country', 'BL', 'Saint Barthélemy';
EXEC SaveClassifier 'Country', 'SH', 'Saint Helena, Ascension and Tristan da Cunha';
EXEC SaveClassifier 'Country', 'KN', 'Saint Kitts and Nevis';
EXEC SaveClassifier 'Country', 'LC', 'Saint Lucia';
EXEC SaveClassifier 'Country', 'MF', 'Saint Martin (French part)';
EXEC SaveClassifier 'Country', 'PM', 'Saint Pierre and Miquelon';
EXEC SaveClassifier 'Country', 'VC', 'Saint Vincent and the Grenadines';
EXEC SaveClassifier 'Country', 'WS', 'Samoa';
EXEC SaveClassifier 'Country', 'SM', 'San Marino';
EXEC SaveClassifier 'Country', 'ST', 'Sao Tome and Principe';
EXEC SaveClassifier 'Country', 'SA', 'Saudi Arabia';
EXEC SaveClassifier 'Country', 'SN', 'Senegal';
EXEC SaveClassifier 'Country', 'RS', 'Serbia';
EXEC SaveClassifier 'Country', 'SC', 'Seychelles';
EXEC SaveClassifier 'Country', 'SL', 'Sierra Leone';
EXEC SaveClassifier 'Country', 'SG', 'Singapore';
EXEC SaveClassifier 'Country', 'SX', 'Sint Maarten (Dutch part)';
EXEC SaveClassifier 'Country', 'SK', 'Slovakia';
EXEC SaveClassifier 'Country', 'SI', 'Slovenia';
EXEC SaveClassifier 'Country', 'SB', 'Solomon Islands';
EXEC SaveClassifier 'Country', 'SO', 'Somalia';
EXEC SaveClassifier 'Country', 'ZA', 'South Africa';
EXEC SaveClassifier 'Country', 'GS', 'South Georgia and the South Sandwich Islands';
EXEC SaveClassifier 'Country', 'SS', 'South Sudan';
EXEC SaveClassifier 'Country', 'ES', 'Spain';
EXEC SaveClassifier 'Country', 'LK', 'Sri Lanka';
EXEC SaveClassifier 'Country', 'SD', 'Sudan (the)';
EXEC SaveClassifier 'Country', 'SR', 'Suriname';
EXEC SaveClassifier 'Country', 'SJ', 'Svalbard and Jan Mayen';
EXEC SaveClassifier 'Country', 'SE', 'Sweden';
EXEC SaveClassifier 'Country', 'CH', 'Switzerland';
EXEC SaveClassifier 'Country', 'SY', 'Syrian Arab Republic';
EXEC SaveClassifier 'Country', 'TW', 'Taiwan (Province of China)';
EXEC SaveClassifier 'Country', 'TJ', 'Tajikistan';
EXEC SaveClassifier 'Country', 'TZ', 'Tanzania, United Republic of';
EXEC SaveClassifier 'Country', 'TH', 'Thailand';
EXEC SaveClassifier 'Country', 'TL', 'Timor-Leste';
EXEC SaveClassifier 'Country', 'TG', 'Togo';
EXEC SaveClassifier 'Country', 'TK', 'Tokelau';
EXEC SaveClassifier 'Country', 'TO', 'Tonga';
EXEC SaveClassifier 'Country', 'TT', 'Trinidad and Tobago';
EXEC SaveClassifier 'Country', 'TN', 'Tunisia';
EXEC SaveClassifier 'Country', 'TR', 'Turkey';
EXEC SaveClassifier 'Country', 'TM', 'Turkmenistan';
EXEC SaveClassifier 'Country', 'TC', 'Turks and Caicos Islands (the)';
EXEC SaveClassifier 'Country', 'TV', 'Tuvalu';
EXEC SaveClassifier 'Country', 'UG', 'Uganda';
EXEC SaveClassifier 'Country', 'UA', 'Ukraine';
EXEC SaveClassifier 'Country', 'AE', 'United Arab Emirates (the)';
EXEC SaveClassifier 'Country', 'GB', 'United Kingdom of Great Britain and Northern Ireland (the)';
EXEC SaveClassifier 'Country', 'UM', 'United States Minor Outlying Islands (the)';
EXEC SaveClassifier 'Country', 'US', 'United States of America (the)';
EXEC SaveClassifier 'Country', 'UY', 'Uruguay';
EXEC SaveClassifier 'Country', 'UZ', 'Uzbekistan';
EXEC SaveClassifier 'Country', 'VU', 'Vanuatu';
EXEC SaveClassifier 'Country', 'VE', 'Venezuela (Bolivarian Republic of)';
EXEC SaveClassifier 'Country', 'VN', 'Viet Nam';
EXEC SaveClassifier 'Country', 'VG', 'Virgin Islands (British)';
EXEC SaveClassifier 'Country', 'VI', 'Virgin Islands (U.S.)';
EXEC SaveClassifier 'Country', 'WF', 'Wallis and Futuna';
EXEC SaveClassifier 'Country', 'EH', 'Western Sahara*';
EXEC SaveClassifier 'Country', 'YE', 'Yemen';
EXEC SaveClassifier 'Country', 'ZM', 'Zambia';
EXEC SaveClassifier 'Country', 'ZW', 'Zimbabwe';
