CREATE PROCEDURE setup.UKPostCodeArea
AS
EXEC SaveClassifier 'UKPostCodeArea', 'AB', 'Aberdeen';
EXEC SaveClassifier 'UKPostCodeArea', 'AL', 'St Albans';
EXEC SaveClassifier 'UKPostCodeArea', 'B', 'Birmingham';
EXEC SaveClassifier 'UKPostCodeArea', 'BA', 'Bath';
EXEC SaveClassifier 'UKPostCodeArea', 'BB', 'Blackburn';
EXEC SaveClassifier 'UKPostCodeArea', 'BD', 'Bradford';
EXEC SaveClassifier 'UKPostCodeArea', 'BF', 'British Forces';
EXEC SaveClassifier 'UKPostCodeArea', 'BH', 'Bournemouth';
EXEC SaveClassifier 'UKPostCodeArea', 'BL', 'Bolton';
EXEC SaveClassifier 'UKPostCodeArea', 'BN', 'Brighton';
EXEC SaveClassifier 'UKPostCodeArea', 'BR', 'Bromley';
EXEC SaveClassifier 'UKPostCodeArea', 'BS', 'Bristol';
EXEC SaveClassifier 'UKPostCodeArea', 'BT', 'Northern Ireland';
EXEC SaveClassifier 'UKPostCodeArea', 'CA', 'Carlisle';
EXEC SaveClassifier 'UKPostCodeArea', 'CB', 'Cambridge';
EXEC SaveClassifier 'UKPostCodeArea', 'CF', 'Cardiff';
EXEC SaveClassifier 'UKPostCodeArea', 'CH', 'Chester';
EXEC SaveClassifier 'UKPostCodeArea', 'CM', 'Chelmsford';
EXEC SaveClassifier 'UKPostCodeArea', 'CO', 'Colchester';
EXEC SaveClassifier 'UKPostCodeArea', 'CR', 'Croydon';
EXEC SaveClassifier 'UKPostCodeArea', 'CT', 'Canterbury';
EXEC SaveClassifier 'UKPostCodeArea', 'CV', 'Coventry';
EXEC SaveClassifier 'UKPostCodeArea', 'CW', 'Crewe';
EXEC SaveClassifier 'UKPostCodeArea', 'DA', 'Dartford';
EXEC SaveClassifier 'UKPostCodeArea', 'DD', 'Dundee';
EXEC SaveClassifier 'UKPostCodeArea', 'DE', 'Derby';
EXEC SaveClassifier 'UKPostCodeArea', 'DG', 'Dumfries and Galloway';
EXEC SaveClassifier 'UKPostCodeArea', 'DH', 'Durham';
EXEC SaveClassifier 'UKPostCodeArea', 'DL', 'Darlington';
EXEC SaveClassifier 'UKPostCodeArea', 'DN', 'Doncaster';
EXEC SaveClassifier 'UKPostCodeArea', 'DT', 'Dorchester';
EXEC SaveClassifier 'UKPostCodeArea', 'DY', 'Dudley';
EXEC SaveClassifier 'UKPostCodeArea', 'E', 'East London';
EXEC SaveClassifier 'UKPostCodeArea', 'EC', 'Central London';
EXEC SaveClassifier 'UKPostCodeArea', 'EH', 'Edinburgh';
EXEC SaveClassifier 'UKPostCodeArea', 'EN', 'Enfield';
EXEC SaveClassifier 'UKPostCodeArea', 'EX', 'Exeter';
EXEC SaveClassifier 'UKPostCodeArea', 'FK', 'Falkirk and Stirling';
EXEC SaveClassifier 'UKPostCodeArea', 'FY', 'Blackpool';
EXEC SaveClassifier 'UKPostCodeArea', 'G', 'Glasgow';
EXEC SaveClassifier 'UKPostCodeArea', 'GL', 'Gloucester';
EXEC SaveClassifier 'UKPostCodeArea', 'GU', 'Guildford';
EXEC SaveClassifier 'UKPostCodeArea', 'HA', 'Harrow';
EXEC SaveClassifier 'UKPostCodeArea', 'HD', 'Huddersfield';
EXEC SaveClassifier 'UKPostCodeArea', 'HG', 'Harrogate';
EXEC SaveClassifier 'UKPostCodeArea', 'HP', 'Hemel Hempstead';
EXEC SaveClassifier 'UKPostCodeArea', 'HR', 'Hereford';
EXEC SaveClassifier 'UKPostCodeArea', 'HS', 'Outer Hebrides';
EXEC SaveClassifier 'UKPostCodeArea', 'HU', 'Hull';
EXEC SaveClassifier 'UKPostCodeArea', 'HX', 'Halifax';
EXEC SaveClassifier 'UKPostCodeArea', 'IG', 'Ilford';
EXEC SaveClassifier 'UKPostCodeArea', 'IP', 'Ipswich';
EXEC SaveClassifier 'UKPostCodeArea', 'IV', 'Inverness';
EXEC SaveClassifier 'UKPostCodeArea', 'KA', 'Kilmarnock';
EXEC SaveClassifier 'UKPostCodeArea', 'KT', 'Kingston upon Thames';
EXEC SaveClassifier 'UKPostCodeArea', 'KW', 'Kirkwall';
EXEC SaveClassifier 'UKPostCodeArea', 'KY', 'Kirkcaldy';
EXEC SaveClassifier 'UKPostCodeArea', 'L', 'Liverpool';
EXEC SaveClassifier 'UKPostCodeArea', 'LA', 'Lancaster';
EXEC SaveClassifier 'UKPostCodeArea', 'LD', 'Llandrindod Wells';
EXEC SaveClassifier 'UKPostCodeArea', 'LE', 'Leicester';
EXEC SaveClassifier 'UKPostCodeArea', 'LL', 'Llandudno';
EXEC SaveClassifier 'UKPostCodeArea', 'LN', 'Lincoln';
EXEC SaveClassifier 'UKPostCodeArea', 'LS', 'Leeds';
EXEC SaveClassifier 'UKPostCodeArea', 'LU', 'Luton';
EXEC SaveClassifier 'UKPostCodeArea', 'M', 'Manchester';
EXEC SaveClassifier 'UKPostCodeArea', 'ME', 'Rochester';
EXEC SaveClassifier 'UKPostCodeArea', 'MK', 'Milton Keynes';
EXEC SaveClassifier 'UKPostCodeArea', 'ML', 'Motherwell';
EXEC SaveClassifier 'UKPostCodeArea', 'N', 'North London';
EXEC SaveClassifier 'UKPostCodeArea', 'NE', 'Newcastle upon Tyne';
EXEC SaveClassifier 'UKPostCodeArea', 'NG', 'Nottingham';
EXEC SaveClassifier 'UKPostCodeArea', 'NN', 'Northampton';
EXEC SaveClassifier 'UKPostCodeArea', 'NP', 'Newport';
EXEC SaveClassifier 'UKPostCodeArea', 'NR', 'Norwich';
EXEC SaveClassifier 'UKPostCodeArea', 'NW', 'North West London';
EXEC SaveClassifier 'UKPostCodeArea', 'OL', 'Oldham';
EXEC SaveClassifier 'UKPostCodeArea', 'OX', 'Oxford';
EXEC SaveClassifier 'UKPostCodeArea', 'PA', 'Paisley';
EXEC SaveClassifier 'UKPostCodeArea', 'PE', 'Peterborough';
EXEC SaveClassifier 'UKPostCodeArea', 'PH', 'Perth';
EXEC SaveClassifier 'UKPostCodeArea', 'PL', 'Plymouth';
EXEC SaveClassifier 'UKPostCodeArea', 'PO', 'Portsmouth';
EXEC SaveClassifier 'UKPostCodeArea', 'PR', 'Preston';
EXEC SaveClassifier 'UKPostCodeArea', 'RG', 'Reading';
EXEC SaveClassifier 'UKPostCodeArea', 'RH', 'Redhill';
EXEC SaveClassifier 'UKPostCodeArea', 'RM', 'Romford';
EXEC SaveClassifier 'UKPostCodeArea', 'S', 'Sheffield';
EXEC SaveClassifier 'UKPostCodeArea', 'SA', 'Swansea';
EXEC SaveClassifier 'UKPostCodeArea', 'SE', 'South East London';
EXEC SaveClassifier 'UKPostCodeArea', 'SG', 'Stevenage';
EXEC SaveClassifier 'UKPostCodeArea', 'SK', 'Stockport';
EXEC SaveClassifier 'UKPostCodeArea', 'SL', 'Slough';
EXEC SaveClassifier 'UKPostCodeArea', 'SM', 'Sutton';
EXEC SaveClassifier 'UKPostCodeArea', 'SN', 'Swindon';
EXEC SaveClassifier 'UKPostCodeArea', 'SO', 'Southampton';
EXEC SaveClassifier 'UKPostCodeArea', 'SP', 'Salisbury';
EXEC SaveClassifier 'UKPostCodeArea', 'SR', 'Sunderland';
EXEC SaveClassifier 'UKPostCodeArea', 'SS', 'Southend-on-Sea';
EXEC SaveClassifier 'UKPostCodeArea', 'ST', 'Stoke-on-Trent';
EXEC SaveClassifier 'UKPostCodeArea', 'SW', 'South West London';
EXEC SaveClassifier 'UKPostCodeArea', 'SY', 'Shrewsbury';
EXEC SaveClassifier 'UKPostCodeArea', 'TA', 'Taunton';
EXEC SaveClassifier 'UKPostCodeArea', 'TD', 'Galashiels';
EXEC SaveClassifier 'UKPostCodeArea', 'TF', 'Telford';
EXEC SaveClassifier 'UKPostCodeArea', 'TN', 'Tonbridge';
EXEC SaveClassifier 'UKPostCodeArea', 'TQ', 'Torquay';
EXEC SaveClassifier 'UKPostCodeArea', 'TR', 'Truro';
EXEC SaveClassifier 'UKPostCodeArea', 'TS', 'Cleveland';
EXEC SaveClassifier 'UKPostCodeArea', 'TW', 'Twickenham';
EXEC SaveClassifier 'UKPostCodeArea', 'UB', 'Southall';
EXEC SaveClassifier 'UKPostCodeArea', 'W', 'West London';
EXEC SaveClassifier 'UKPostCodeArea', 'WA', 'Warrington';
EXEC SaveClassifier 'UKPostCodeArea', 'WC', 'Central London';
EXEC SaveClassifier 'UKPostCodeArea', 'WD', 'Watford';
EXEC SaveClassifier 'UKPostCodeArea', 'WF', 'Wakefield';
EXEC SaveClassifier 'UKPostCodeArea', 'WN', 'Wigan';
EXEC SaveClassifier 'UKPostCodeArea', 'WR', 'Worcester';
EXEC SaveClassifier 'UKPostCodeArea', 'WS', 'Walsall';
EXEC SaveClassifier 'UKPostCodeArea', 'WV', 'Wolverhampton';
EXEC SaveClassifier 'UKPostCodeArea', 'YO', 'York';
EXEC SaveClassifier 'UKPostCodeArea', 'ZE', 'Lerwick';
