CREATE TABLE internal.Code (
    CodeID INT NOT NULL DEFAULT NEXT VALUE FOR internal.Identifier
  , CodeValue NVARCHAR(500) NOT NULL
  , CONSTRAINT PK_Code PRIMARY KEY (CodeID)
  , CONSTRAINT UQ_Code UNIQUE (CodeValue)
)
